yezyilomo/django-restql

README.md
django_restql/mixins.py
tests/test_views.py

Remove nested list on query param

---

django_restql/mixins.py

- Fix bug
- Improve format of the code

Fix not checking field_name on is_top_list_request

---

setup.py

- Add exclude(-) and wildcard(*) operators on query, Closed #70 
- Add DynamicSerializerMethod, Closed #57

Release v0.6.0

---

django_restql/fields.py
tests/test_views.py

Fix case where query isn't present for DynamicSerializerMethodField

---

setup.py

- Selecting and Prefetching related fields dynamically with 'EagerLoadingMixin`, closed #63 
- Bug on `DynamicSerializerMethodField`, closed #76

Release v0.7.0

---

README.md
docs/extra.css
docs/index.md
setup.py

- Add `restql_settings` object and corresponding Django setting variable named `RESTQL` for all **Django RESTQL** configurations, Closed #84 
- Add `QUERY_PARAM_NAME` for configuring restql query parameter name, Closed #84
- Make `EagerLoadingMixin` independent of `DynamicFieldsMixin`, Closed #86

Release v0.7.1

---

django_restql/mixins.py
docs/index.md
tests/test_views.py
tests/testapp/views.py
tests/urls.py

Fix bug when using EagerLoadingMixin and only a Prefetch object

---

django_restql/mixins.py
django_restql/settings.py
docs/index.md

Add property to allow optional applying of eager loading by default

---

django_restql/mixins.py
docs/index.md
setup.py
tests/test_views.py
tests/testapp/views.py
tests/urls.py

- Add `AUTO_APPLY_EAGER_LOADING` setting and `auto_apply_eager_loading` view attribute, Closed #85 
- Fixed #90 
- Fixed #93 
- Fixed #98

Release v0.7.2

---

django_restql/__init__.py
setup.py

Release v0.7.3

---

django_restql/fields.py
django_restql/mixins.py

- This is for highlighting areas which needs improvements and fixes

Add TODO and FIXME tags on source code

---

django_restql/__init__.py

- #106 
- #107 
- #110 
- #111

Release v0.7.4

---

django_restql/__init__.py

- Add query arguments, #117
- Add `disable_dynamic_fields` kwarg to `DynamicFieldsMixin`, #121 
- #116

Release v0.8.0

---

django_restql/fields.py
django_restql/mixins.py
tests/test_views.py

Fix breaking partial update

---

django_restql/__init__.py

Release v0.9.0

---

django_restql/fields.py
django_restql/mixins.py
tests/test_views.py
tests/testapp/serializers.py
tests/testapp/views.py
tests/urls.py

Fix post req on nested field

---

django_restql/__init__.py
django_restql/fields.py
django_restql/mixins.py
tests/test_views.py
tests/testapp/serializers.py
tests/testapp/views.py
tests/urls.py

Release v0.9.1

---

django_restql/__init__.py
django_restql/parser.py
docs/querying_data.md
tests/test_views.py
tests/testapp/views.py

Release v0.9.2

---

django_restql/__init__.py
django_restql/mixins.py
docs/mutating_data.md

- #163 
- Deprecate `DEFAULT_BASE_FILTER_BACKEND` setting

Release v0.10.0

---

django_restql/__init__.py

Release v0.10.1

---

django_restql/fields.py

🐛Fix a bug causing create_ops and update_ops kwargs not to work

---

django_restql/__init__.py

🔖Release v0.10.2

---

django_restql/__init__.py

- Support sending data and pk when `accept_pk=True`( #190, #187 )
- Add `accept_pk_only` kwarg

🔖Release v0.11.0

---

django_restql/__init__.py

Release v0.11.1

---

django_restql/__init__.py

Release v0.11.2

---

django_restql/fields.py
django_restql/mixins.py
django_restql/parser.py
django_restql/settings.py
docs/querying_data.md
docs/settings.md
tests/test_views.py

This will allow users to rename fields through query just like in [GraphQL](https://graphql.org/learn/queries/#aliases)

Add rename/alias functionality

---

django_restql/__init__.py
docs/querying_data.md

- Add rename/alias functionality #209 
- #211 
- #213 
Thanks to @nielslerches, @resurrexi and @sommelon for raising issues which have all been resolved in this release.

Release v0.12.0

---

django_restql/fields.py
django_restql/mixins.py
django_restql/parser.py
tests/test_views.py

Allow including and excluding fields on the same field level

---

django_restql/__init__.py

- Make `DynamicFieldsSerializer` independent of request(add query and parsed_query kwargs) #225 
- Allow including and excluding fields on the same field level #222 
- #223 
- #221  
Thanks to @diegoduncan21 and @yezyilomo for raising issues which have all been resolved in this release.

Release v0.13.0

---

django_restql/mixins.py

- This happens when request is not None and request query parameter is not passed
- Fixes #241

Fix ignoring query & parsed_query kwargs

---

django_restql/parser.py

Fix QuerySyntaxError if the value of query argument is empty string

---

django_restql/__init__.py
django_restql/fields.py

Release v0.13.1

---

django_restql/fields.py

- The error occur if a nested serializer is using fields = '__all__'

Fix error when creating/updating ManyToOne nested field

---

django_restql/fields.py
django_restql/mixins.py
tests/test_views.py
tests/testapp/models.py
tests/testapp/serializers.py

Implementation details are as per #185

Add a way to define a self referencing nested field

---

django_restql/fields.py
django_restql/mixins.py
django_restql/parser.py

Improve parsed query format and performance

---

django_restql/mixins.py

Fix patching nested object to its parent

---

django_restql/__init__.py
django_restql/mixins.py

- #300 
- Remove unused code(Unused returns)
- Avoid calling `instance.save` unnecessarily as discussed on #301

Release v0.15.2

---

django_restql/__init__.py

- Python v3.10 & v3.11
- Django v4.0 & v4.1 
- DRF v3.13 & v3.14

Release v0.15.3

---

django_restql/__init__.py

Release v0.15.4

---

django_restql/__init__.py

Release v0.16.0

---

django_restql/mixins.py

Make generic relation support optional

---

django_restql/__init__.py

Release v0.16.1

---

django_restql/mixins.py

Fix import issue on generic rel support
